ENV CARGO_HOME=/cargo \
    RUSTUP_HOME=/rustup \
    PATH=/cargo/bin:$PATH

RUN echo $PATH && \
    yum -y install curl git && \
    yum -y install centos-release-scl && yum -y install llvm-toolset-7 && \
    mkdir -p $CARGO_HOME && mkdir -p $RUSTUP_HOME && \
    curl -fsS https://sh.rustup.rs > /rustup-init.sh && chmod +x /rustup-init.sh && \
    sh /rustup-init.sh -v -y --no-modify-path --default-toolchain nightly && \
    rustup component add --toolchain nightly rust-src rustfmt
