RUN echo $PATH && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends ca-certificates curl git build-essential python3 python3-pip python3-setuptools python3-venv
